### ISSUE TITLE
Error running script without sudo

### ISSUE THREAD

**Issue by taten14** [ValdikSS/windows2usb#1]
When i run the script without sudo gives me this error

== Extracting files from ISO to the partition ==

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=C,Utf16=off,HugeFiles=on,4 CPUs)

Error:
there is no such archive

But when i run it with sudo it works perfectly!

SO
Distributor ID: neon
Description:    KDE neon User Edition 5.12
Release:        16.04
Codename:       xenial

Kernel: 4.13.0-39-generic

**Comment by ValdikSS** [comment]
Do you see graphical password prompt if you run the script without sudo?

**Comment by taten14** [comment]
Yes, this is after i put my credentials in

**Comment by ValdikSS** [comment]
I think I fixed it. Can you please try v0.1.2?

**Comment by taten14** [comment]
Works excelent!!
