### ISSUE TITLE
Target NTFS file system mounts in read only mode

### ISSUE THREAD

**Issue by polezaivsani** [ValdikSS/windows2usb#13]
When the target NTFS file system is being mounted at [https://github.com/ValdikSS/windows2usb/blob/master/windows2usb#L199](), `mount` (as well as `mount -t ntfs -o rw`) would mount file system in read only mode.  Yet if i do it via ntfs-3g helper directly (`mount.ntfs` or `mount.ntfs-3g`) everything works as expected.

I don't have a good fix for it, but would be willing to dig this deeper should somebody has any ideas on how to fix it.

**Comment by ValdikSS** [comment]
I suppose with `mount -t ntfs` kernel NTFS driver is used, which is simple and does support writing to the FS.
In most distros mouting NTFS is done by ntfs-3g. Could it be you have misconfigured system?

**Comment by polezaivsani** [comment]
Yeah, i believe you're right.  I do have both kernel module and ntfs-3g on machine where i ran into the issue.  The fact that `mount -t ntfs -o rw` does succeeds with 0 result code, but just silently mounts it in read-only seems wrong to me.

Guess there is little value in accounting for such odd case here.  Please close this as needed.  And much thanks for the thing in the first place (and modded BIOS too) :)

**Comment by ValdikSS** [comment]
What distro do you use?

**Comment by polezaivsani** [comment]
That happened on NixOS 20.03.  Before that i ran it successfully on a Gentoo with kernel without NTFS module.

**Comment by ar0177417** [comment]
First try ntfsfix/dev/sdxx and then try ntfs-3g mount /dev/sdxx
It always works for me

**Comment by ValdikSS** [comment]
Should be fixed in new version.
