### ISSUE TITLE
MacOS version

### ISSUE THREAD

**Issue by a0s** [ValdikSS/windows2usb#14]
Hi! Any chance to have this tool compiled as Mac OS's binary ?

**Comment by ValdikSS** [comment]
I don't know much about macOS and I don't own mac. I'm not sure whether this script could be used as-is, because it requires `lsblk`, `sfdisk`, `mkfs.ntfs` and other software, which I assume is Linux-only.

**Comment by yurikoles** [comment]
We don't have `lsblk` on macOS, but we have a [`gdisk`](https://formulae.brew.sh/cask/gdisk) on mac via Homebrew Cask. And [`ntfs-3g`](https://formulae.brew.sh/formula/ntfs-3g) via Homebrew that works via [`osxfuse`](https://formulae.brew.sh/cask/osxfuse). But nevertheless, my main concern is `ms-sys`, which is essential for legacy BIOS / UEFI CSM and I was unable to build it under macOS. Project seems to be abandoned.
