### ISSUE TITLE
How to install recent Windows 10 versions with Secure Boot?

### ISSUE THREAD

**Issue by spiralw** [ValdikSS/windows2usb#18]
Hi, I'm trying to reinstall Windows 10 on a machine with Secure Boot. I downloaded the latest windows 10 ISO, and I get the error `install.wim is greater than 4 GiB, please use gptntfs mode`. I can't use gptntfs, since I need secure boot to work. What are my options? Thanks

**Comment by ValdikSS** [comment]
You can disable Secure Boot for installation and enable it later.

**Comment by ValdikSS** [comment]
If you don't want to disable Secure Boot for some reason (you certainly can, this is a requirement for all x86 motherboards), then windows2usb won't suit your needs, and you'll need to use another utility which can split .wim file.

**Comment by spiralw** [comment]
Ok, thanks for your help.
