### ISSUE TITLE
appimagelauncherfs/0000.AppImage: Permission denied

### ISSUE THREAD

**Issue by vlad88sv** [ValdikSS/windows2usb#19]
✦ ❯ ./windows2usb-0.2-x86_64.AppImage /dev/sdc Jaque/win10.iso mbr
Error accessing /run/user/1000/appimagelauncherfs/0000.AppImage: Permission denied

Ubuntu 21.04

Thanks

**Comment by ValdikSS** [comment]
I would guess you have /run mounted with noexec.
