### ISSUE TITLE
GPT Option does not work

### ISSUE THREAD

**Issue by taten14** [ValdikSS/windows2usb#2]
Command: windows2usb /dev/sdb ./ISOS/SW_DVD9_Win_Pro_10_1709.1_64BIT_Spanish_Pro_Ent_EDU_N_MLF_X21-67528.ISO gpt

Mountpoint: /run/windows2usb.LPXdS4sw2m

 == Removable storage list ==
/dev/sdb  14.4G DT microDuo 3.0

Kernel: 4.13.0-39-generic
SO: KDE neon 5.12
...
Extracting  sources/inf/setup.cfg
Extracting  sources/input.dll
Extracting  sources/install.wim
ERROR: E_FAIL

**Comment by ValdikSS** [comment]
Please provide uncut log and also `7z l ./ISOS/SW_DVD9_Win_Pro_10_1709.1_64BIT_Spanish_Pro_Ent_EDU_N_MLF_X21-67528.ISO`

**Comment by taten14** [comment]
I just upload 2 files. One with the full log of the command with the GPT option, and other with the 7z l you asked for.


[7z-l.txt](https://github.com/ValdikSS/windows2usb/files/1980500/7z-l.txt)
[full-log.txt](https://github.com/ValdikSS/windows2usb/files/1980501/full-log.txt)

Thanks!!!!!!

**Comment by taten14** [comment]
2017-12-13 22:07:38 .....   4377962627   4377964544  sources/install.wim

mkfs.fat 3.0.28 (2015-05-16)

I think that sources/install.wim is too long to an FAT parttion. Isn't?

**Comment by ValdikSS** [comment]
You're right, please try v0.1.3, should be fixed.

**Comment by taten14** [comment]
This is my version of sfdisk de util-linux 2.27.1 it does not support the U option.
 ...
              The partition type is given in hex for MBR (DOS), without the 0x prefix, a GUID string for GPT, or a shortcut:

                     L      Linux; means 83 for MBR and 0FC63DAF-8483-4772-8E79-3D69D8477DE4 for GPT.

                     S      swap area; means 82 for MBR and 0657FD6D-A4AB-43C4-84E5-0933C84B4F4F for GPT

                     E      extended partition; means 5 for MBR

                     H      home partition; means 933AC7E1-2EB4-4F13-B844-0E14E2AEF915 for GPT

                     X      linux extended partition; means 85 for MBR.

              The default type value is L
...

sfdisk's Man Page

**Comment by ValdikSS** [comment]
Please use AppImage, it has latest sfdisk inside the bundle.

**Comment by ValdikSS** [comment]
@taten14 does appimage work for you?

**Comment by taten14** [comment]
My distro gets broke. I dont know if was after appimage upgrade or compiling latest linux-utils version. Im reconfiguring all right now. :)
