### ISSUE TITLE
/etc/fstab should be restored automatically

### ISSUE THREAD

**Issue by AB-70** [ValdikSS/windows2usb#20]
The application doesn't restore the **/etc/fstab** automatically when its finished making the USB bootable, thus making the system UNBOOTABLE once its halted. My workaround was to backup the original **/etc/fstab** and then restore it after I am done making the USB bootable.

**Comment by ValdikSS** [comment]
The application does not edit /etc/fstab in any way, nor it access it.
How do you use the script and what exactly happens?

**Comment by AB-70** [comment]
I ran the script just as you would run any script, it did left the fstab modified with an entry of type exFat having unknown UUID, but I tried to reproduce the issue and it doesn't happen again. I also got the following error while burning Windows 7 in MBR mode. I don't know why it happened the first time and even yesterday when I was using it again. 
```
--OUTPUT TRUNCATED--
Folders: 200
Files: 870
Size:       4001683580
Compressed: 4002959360
Splitting WIM: 3481 MiB of 3481 MiB (100%) written, part 1 of 1
Finished splitting "/run/windows2usb-mount.tSyauyC620/sources/install.wim"
 == Extracting UEFI bootloader from install.wim ==

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
                                              
ERROR: No more files
/run/windows2usb.htebtZLo8G/sources/install.wim



System ERROR:
Unknown error -2147024872
```

**Comment by AB-70** [comment]
I ran the script just as you would run any script, it did left the fstab modified with an entry of type exFat having unknown UUID, but I tried to reproduce the issue and it doesn't happen again. I also got the following error while burning Windows 7 in MBR mode. I don't know why it happened the first time and even yesterday when I was using it again. 
```
--OUTPUT TRUNCATED--
Folders: 200
Files: 870
Size:       4001683580
Compressed: 4002959360
Splitting WIM: 3481 MiB of 3481 MiB (100%) written, part 1 of 1
Finished splitting "/run/windows2usb-mount.tSyauyC620/sources/install.wim"
 == Extracting UEFI bootloader from install.wim ==

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
                                              
ERROR: No more files
/run/windows2usb.htebtZLo8G/sources/install.wim



System ERROR:
Unknown error -2147024872
```

**Comment by ValdikSS** [comment]
I would guess you have a system daemon which detects new devices/partitions, mounts them and changes fstab. Disable it.

**Comment by ValdikSS** [comment]
What's your OS by the way?
