### ISSUE TITLE
The program does not understand Cyrillic characters in images

### ISSUE THREAD

**Issue by leoneii** [ValdikSS/windows2usb#21]
for example:

"ERROR: Can not open output file : Invalid argument : /run/windows2usb.mRzXRGJTqE/JINN/WinSetup/OEM/10_$OEM$/$$/Setup/Scripts/Tweaks/????????? ?????? ?????????? ????????? ? ??????????? ???? ''???? ?????????''.reg"

**Comment by recolic** [comment]
Could you attach the full log, or provide a ISO file, so I can perform a test?

**Comment by ValdikSS** [comment]
The issue is probably caused by LANG=C. Unicode locale should be used for unpacking.

**Comment by ValdikSS** [comment]
Try to replace `LANG=C` with `LANG=C.UTF-8` in the top of the script.

**Comment by ValdikSS** [comment]
@leoneii, kindly waiting for more information of your ISO file and whether `LANG=C.UTF-8` worked.
