### ISSUE TITLE
System ERROR: -2147024872

### ISSUE THREAD

**Issue by kumaraish** [ValdikSS/windows2usb#25]
windows2usb terminated with this error. Here is the log.

ubuntu@ubuntu:~$ sudo ./windows2usb /dev/sda 7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_PROFESSIONAL_x64FRE_en-us.iso mbr
 == Working with ISO DVD_ROM ==
 == Creating new MBR-formatted partition table ==
Checking that no-one is using this disk right now ... OK

Disk /dev/sda: 15.12 GiB, 16236150784 bytes, 31711232 sectors
Disk model: v210w
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x7604966e

Old situation:

Device     Boot Start      End  Sectors  Size Id Type
/dev/sda1  *     2048 31709183 31707136 15.1G  7 HPFS/NTFS/exFAT

>>> Script header accepted.
>>> Done.
Created a new DOS disklabel with disk identifier 0x2696ad7d.

New situation:
Disklabel type: dos
Disk identifier: 0x2696ad7d

The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
 == Waiting 3 seconds to settle new partition layout ==
 == Creating FAT partition ==
Checking that no-one is using this disk right now ... OK

Disk /dev/sda: 15.12 GiB, 16236150784 bytes, 31711232 sectors
Disk model: v210w
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x2696ad7d

Old situation:

>>> Created a new DOS disklabel with disk identifier 0xa14d1122.
/dev/sda1: Created a new partition 1 of type 'HPFS/NTFS/exFAT' and of size 15.1 GiB.
/dev/sda2: Done.

New situation:
Disklabel type: dos
Disk identifier: 0xa14d1122

Device     Boot Start      End  Sectors  Size Id Type
/dev/sda1  *     2048 31711231 31709184 15.1G  7 HPFS/NTFS/exFAT

The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
mkfs.fat 4.1 (2017-01-24)
 == Writing bootloader ==
Windows 7 master boot record successfully written to /dev/sda
FAT32 PE boot record successfully written to /dev/sda1
 == Mounting data partition ==
 == NOTE: install.wim is greater than 4 GiB and will be split to fit FAT32 limit ==
 == Extracting files from ISO to the partition ==

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,4 CPUs LE)

Scanning the drive for archives:
1 file, 5898725376 bytes (5626 MiB)

Extracting archive: 7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_PROFESSIONAL_x64FRE_en-us.iso

Path = 7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_PROFESSIONAL_x64FRE_en-us.iso
Type = Udf
Physical Size = 5898725376
Comment = DVD_ROM
Cluster Size = 2048
Created = 2018-11-27 00:00:00

Everything is Ok

Folders: 199
Files: 876
Size:       382937727
Compressed: 5898725376
Writing "/run/windows2usb.6rKeMHadLi/sources/install.swm" (part 1 of 2): 0 MiB of 5251 MiB (0%) written
Writing "/run/windows2usb.6rKeMHadLi/sources/install2.swm" (part 2 of 2): 3798 MiB of 5251 MiB (72%) written
Finished writing split WIM part 2 of 2
 == Extracting UEFI bootloader from install.wim ==

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,4 CPUs LE)

Scanning the drive for archives:

ERROR: No more files
/run/windows2usb.6rKeMHadLi/sources/install.wim

System ERROR:
Unknown error -2147024872

**Comment by ValdikSS** [comment]
Try https://github.com/ValdikSS/windows2usb/commit/68b616a916ca0013ac4356bab2042ad764740f28, it should work.
