### ISSUE TITLE
UEFI-NTFS for FAT32 part

### ISSUE THREAD

**Issue by tfastgame** [ValdikSS/windows2usb#28]
RUS:
Раздел в 1 мегабайт с UEFI-NTFS создается если пользователь выбрал как файловую систему FAT32? Или этот загрузчик грузит только если FS = NTFS?

ENG:
Is the 1 megabyte partition with UEFI-NTFS created if the user selected FAT32 as the file system? Or does this loader only load if FS = NTFS?

**Comment by ValdikSS** [comment]
UEFI-NTFS используется только в режиме `gpt+uefintfs`, GPT+NTFS(data)+FAT32(efi).
