### ISSUE TITLE
Where and how do you install the legacy-boot boot loader?

### ISSUE THREAD

**Issue by tfastgame** [ValdikSS/windows2usb#29]
I have been trying to rewrite your code in C# for over 2 weeks now, and I am almost 70% successful. But I still can't figure out where you have legacy boot loader installation for NTFS and FAT32 file system. Can you poke me in this code? Or write me a command template to install legacy-boot loader.

Thank you in advance

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/windows2usb/blob/9f855faabd9f33998b3c773927311510877f15a6/windows2usb#L255-L256
