### ISSUE TITLE
Помогите пожалуйста довести адаптацию вашего приложения на C#.

### ISSUE THREAD

**Issue by tfastgame** [ValdikSS/windows2usb#30]
Вы когда-то отправили сей репозиторий мне в ответ на вопрос на Хабре. Я решил переписать ваше приложение на C#, и начал с самого сложного на мой взгляд - части с NTFS. И при записи ошибок не возникает. Но ни легаси бут, ни УЕФИ не работает. Не могли бы вы ознакомится с кодом по [этой ссылке](https://github.com/tfastgame/Rufus-For-Linux-Core/blob/main/Init.cs), и высказать свои замечания, или предложения? Очень хотелось бы довести проект до конца.

**Comment by ValdikSS** [comment]
Ваш код только выполняет команды. Попробуйте выполнить их вручную в терминале и посмотрите, где может быть ошибка.
Журнал выполнения всех команд самого скрипта windows2usb можно получить, добавив `set -x` в самый верх файла.
