### ISSUE TITLE
System ERROR: -2147024872

### ISSUE THREAD

**Issue by KR1470R** [ValdikSS/windows2usb#32]
Scanning the drive for archives:
                                                    
ERROR: No more files
/run/windows2usb-mount.tCjXRX6C17/sources/install.esd

System ERROR:
Unknown error -2147024872

**Comment by ValdikSS** [comment]
What is that? Paste the full output.

**Comment by KR1470R** [comment]
== Working with ISO GRMCULXFRER_EN_DVD ==
 == Creating new MBR-formatted partition table ==
Checking that no-one is using this disk right now ... OK

Disk /dev/sdb: 7.5 GiB, 8022654976 bytes, 15669248 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x8cef5827

Old situation:

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdb1  *     2048 15669247 15667200  7.5G  7 HPFS/NTFS/exFAT

>>> Script header accepted.
>>> Done.
Created a new DOS disklabel with disk identifier 0x2780386c.

New situation:
Disklabel type: dos
Disk identifier: 0x2780386c

The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
 == Creating FAT partition ==
Checking that no-one is using this disk right now ... OK

Disk /dev/sdb: 7.5 GiB, 8022654976 bytes, 15669248 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x2780386c

Old situation:

>>> Created a new DOS disklabel with disk identifier 0x24ac1e4f.
/dev/sdb1: Created a new partition 1 of type 'HPFS/NTFS/exFAT' and of size 7.5 GiB.
Partition #1 contains a vfat signature.
/dev/sdb2: Done.

New situation:
Disklabel type: dos
Disk identifier: 0x24ac1e4f

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdb1  *     2048 15669247 15667200  7.5G  7 HPFS/NTFS/exFAT

The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
mkfs.fat 4.2 (2021-01-31)
 == Writing bootloader ==
Windows 7 master boot record successfully written to /dev/sdb
FAT32 PE boot record successfully written to /dev/sdb1
 == Mounting data partition ==
 == Extracting files from ISO to the partition ==

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 3319478272 bytes (3166 MiB)

Extracting archive: /home/kript/Downloads/en_windows_7_ultimate_x64_dvd.iso
--           
Path = /home/kript/Downloads/en_windows_7_ultimate_x64_dvd.iso
Type = Udf
Physical Size = 3319478272
Comment = GRMCULXFRER_EN_DVD
Cluster Size = 2048
Created = 2010-11-21 11:33:27

Everything is Ok                               

Folders: 199
Files: 877
Size:       3335912558
Compressed: 3319478272
 == Extracting UEFI bootloader from install.wim ==

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
                                                    
ERROR: No more files
/run/windows2usb-mount.OCvT0oWWiG/sources/install.esd



System ERROR:
Unknown error -2147024872

**Comment by KR1470R** [comment]
actually this error doesn't affect on result flashboot as i can see, but anyway

**Comment by ValdikSS** [comment]
Which file does the ISO file contain, sources/install.wim or sources/install.esd?
Does that file contain 1/Windows/Boot/EFI/bootmgfw.efi or 2/Windows/Boot/EFI/bootmgfw.efi file?

**Comment by KR1470R** [comment]
1) the ISO file contains sources/install.wim.
2) none of these, i see bootmgr.efi.

**Comment by ValdikSS** [comment]
I guess you have a customized non-original ISO then. Is that correct?

**Comment by KR1470R** [comment]
yep

**Comment by KR1470R** [comment]
since i've been using your tool long and i getting this error sometimes, but it seems non-critical and the tool works very well tho.

**Comment by ValdikSS** [comment]
Well, the ISO is broken then. It lacks proper efi bootloader. It would work only in BIOS boot.

**Comment by KR1470R** [comment]
u know... that's may be right, because i've noticed that this ISO file works only on legacy bios, not UEFI, maybe this is because of old laptop or i dunno. okay then no problem ^-^

**Comment by ValdikSS** [comment]
Fixed in 0.2.3.
