### ISSUE TITLE
Win7 issue

### ISSUE THREAD

**Issue by dimez** [ValdikSS/windows2usb#35]
I'm trying to make a flash from en_windows_7_professional_with_sp1_vl_build_x64_dvd_u_677791.iso
(I used 0.2.1 and 0.2.2)
Got a strange error:
 == Extracting UEFI bootloader from install.wim ==

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
ERROR: No more files
/run/windows2usb-mount.NSAXkgmW5e/sources/install.esd
System ERROR:
Unknown error -2147024872

**Comment by ValdikSS** [comment]
Bash is just [unbelievable](https://stackoverflow.com/a/321352), just as my errors.
Fixed in 0.2.3.

**Comment by ValdikSS** [comment]
Your ISO doesn't have .efi bootloader, as it appears. I'm downloading it right now, will check.
Your installation should be working, it failed right in the last step, just make sure to unmount the ISO manually.

**Comment by ValdikSS** [comment]
Fixed in 0.2.4
