### ISSUE TITLE
"Не найден необходимый драйвер носителя" в Win10_22H2_Russian_x64.iso

### ISSUE THREAD

**Issue by ilyaigpetrov** [ValdikSS/windows2usb#37]
При записи был использован способ по умолчанию: mbr mode.
Версия 0.2.4.
Флешка: 16GB Transcend.

![win2usb-Win10_22H2_Russian_x64](https://github.com/ValdikSS/windows2usb/assets/1090811/bb399398-caf2-43ba-8bbf-6a1ed436310c)

**Comment by yurikoles** [comment]
А при чём тут `windows2usb`? Если ты загрузился с флешки и дошёл до этого сообщение, значит флешка создана корректно, но в WinPE нет дров для твоего железа.

**Comment by yurikoles** [comment]
Если сомневаешься, то попробуй пробросить эту флешку в любую виртуальную машину, например QEMU, и загрузись с неё.

**Comment by ValdikSS** [comment]
> А при чём тут `windows2usb`?

Такое иногда бывает из-за неправильного идентифкатора раздела, но, вроде, я это устранял.

**Comment by ilyaigpetrov** [comment]
Ноутбук старый, раньше на нём win10 через `windows2usb` ставился без проблем.
Возможно, дело в том, что он только что из ремонта и на нём была перепаяна звуковая карта.
Думаю, могли задеть что-то паяльником, из-за чего у winPE стал возникать конфликт с железом.

**Comment by ilyaigpetrov** [comment]
Сменил флешку -- заработало.
Спасибо за удобный инструмент и поддержку.
