### ISSUE TITLE
Need to use double quotes while address "/path to off-topic.iso"

### ISSUE THREAD

**Issue by DragonSerW** [ValdikSS/windows2usb#38]
Hello ValdikSS!
Your program is a charm!
It works, I can perform Off-topic installation media while on my Fedora! )
I found information about your application in linux.org.ru/forum, btw :-)

So my question is: when I perform this command the scripts works well:
`
[dragonserw@fedora ~]$ cd $HOME/Public/ValdikSS && ./windows2usb-0.2.4-x86_64.AppImage /dev/sdb "$HOME/Public/_iso-Off-topic/Windows 10 Enterprise LTSC 2021/ru-ru_windows_10_enterprise_ltsc_2021_x64_dvd_5044a1e7.iso"
`
But if I change double quotes to single quotes, this message appears:
` == ERROR: ISO file not found! ==`

This is not huge problem, but please add information about need using double quotes in to the README.md of Windows2usb :-)

**Comment by ValdikSS** [comment]
https://stackoverflow.com/a/21192458/9974656
