### ISSUE TITLE
Command "windows2usb" not recognized on KDE Neon (Ubuntu 16.04.4)

### ISSUE THREAD

**Issue by mariojuniorjp** [ValdikSS/windows2usb#5]
Hi. I trying to use this tool, but the command "windows2usb" is not recognized. 

`botnet@nsa:~/Downloads$ windows2usb /dev/sdd Win10_1803_BrazilianPortuguese_x64.iso gpt
windows2usb: command not found`

**Comment by ValdikSS** [comment]
Since `Downloads` folder is not in your PATH variable, you need to run it like `./windows2usb`
