### ISSUE TITLE
mv: cannot stat '/run/windows2usb.790IvlMoCf/efi/boot/bootmgfw.efi': No such file or directory

### ISSUE THREAD

**Issue by saikat0511** [ValdikSS/windows2usb#9]
I downloaded the appimage file, made it executable and ran it by 

`./windows2usb.AppImage /dev/sdb win7.iso gptntfs` 

After copying the files it results in the error in the title. I am using a windows7 iso. What am I doing wrong??

**Comment by ValdikSS** [comment]
Please provide full output of the program.

**Comment by ValdikSS** [comment]
Any update?

**Comment by saikat0511** [comment]
> 
> 
> Any update?

Sorry for the late reply. Ended up using another windows pc to create the iso.

But I remember that I extracted the win7 iso to check if the bootmgfw.efi file was present. It was not. I checked a win10 iso, it was present in there. I am no developer but my guess is that it has something to do with win7 messy support for gpt and efi

**Comment by ValdikSS** [comment]
Could it be you used a very very old Windows 7 ISO or incorrectly made custom build? Official Windows 7 SP1 ISO contains this file.
Let's decide that windows2usb only works with the latest Windows 7 SP1 official ISO in UEFI mode then.
